from fridge.models import Calories, Carbs, Fats, Protein, Sodium, Sugar
from django.utils import timezone

cal = Calories(amount=1400, eaten_date=timezone.now())
cal.save()
cal = Calories(amount=1200, eaten_date=timezone.now())
cal.save()
cal = Calories(amount=1100, eaten_date=timezone.now())
cal.save()
cal = Calories(amount=1500, eaten_date=timezone.now())
cal.save()
cal = Calories(amount=900, eaten_date=timezone.now())
cal.save()

carbs = Carbs(amount=1800, eaten_date=timezone.now())
carbs.save()
carbs = Carbs(amount=1500, eaten_date=timezone.now())
carbs.save()
carbs = Carbs(amount=1100, eaten_date=timezone.now())
carbs.save()
carbs = Carbs(amount=1000, eaten_date=timezone.now())
carbs.save()
carbs = Carbs(amount=1400, eaten_date=timezone.now())
carbs.save()

fats = Fats(amount=1000, eaten_date=timezone.now())
fats.save()
fats = Fats(amount=900, eaten_date=timezone.now())
fats.save()
fats = Fats(amount=1200, eaten_date=timezone.now())
fats.save()
fats = Fats(amount=1500, eaten_date=timezone.now())
fats.save()
fats = Fats(amount=1300, eaten_date=timezone.now())
fats.save()

protein = Protein(amount=1100, eaten_date=timezone.now())
protein.save()
protein = Protein(amount=900, eaten_date=timezone.now())
protein.save()
protein = Protein(amount=1300, eaten_date=timezone.now())
protein.save()
protein = Protein(amount=1500, eaten_date=timezone.now())
protein.save()
protein = Protein(amount=1800, eaten_date=timezone.now())
protein.save()

sodium = Sodium(amount=800, eaten_date=timezone.now())
sodium.save()
sodium = Sodium(amount=1500, eaten_date=timezone.now())
sodium.save()
sodium = Sodium(amount=1300, eaten_date=timezone.now())
sodium.save()
sodium = Sodium(amount=1100, eaten_date=timezone.now())
sodium.save()
sodium = Sodium(amount=900, eaten_date=timezone.now())
sodium.save()

sugar = Sugar(amount=1400, eaten_date=timezone.now())
sugar.save()
sugar = Sugar(amount=1100, eaten_date=timezone.now())
sugar.save()
sugar = Sugar(amount=1300, eaten_date=timezone.now())
sugar.save()
sugar = Sugar(amount=1000, eaten_date=timezone.now())
sugar.save()
sugar = Sugar(amount=1500, eaten_date=timezone.now())
sugar.save()

